### ISSUE TITLE
ENOTEMPTY during second run

### ISSUE THREAD

**Issue by ezoushen** [amyu/setup-android#220]
I bumped into this error during my second run with cache disabled.
<img width="1110" alt="Screenshot 2023-11-21 at 5 32 38 PM" src="https://github.com/amyu/setup-android/assets/52528244/96d40207-f7b0-43f5-b5fa-a2f2e5741334">
It seems like the error came from these lines. 
https://github.com/amyu/setup-android/blob/5f197ed38cae1de329c286f729d93d041e91df1d/src/installer.ts#L80-L83
Did I misconfigure some things or how could I fix this? Many thanks.

**Comment by ezoushen** [comment]
Running on 2020 M1 Mac Mini (MacOS Ventura 13.6)

**Comment by amyu** [comment]
:eyes:

**Comment by amyu** [comment]
@ezoushen 
I understand this Issue.
I think that your SelfHostedRunner environment does not run a new Instance for each Workflow run.
For example, in GithubHostedRunner, a new Instance is launched for each Workflow, so you need to set up your environment, such as java, using setup-java!

The solution to this problem is simple.
Instead of using amyu/setup-android to set up the Android SDK, we recommend setting it up directly in the on-premises Mac environment.

**Comment by amyu** [comment]
However, we understand that setting up the Android SDK in an on-premise environment is often a difficult task, such as updating the SDK
Adding a simple cleanup process is no different from the Library's policy, and we will do so immediately.
The schedule for inclusion in v3 has not yet been determined, so please specify amyu/setup-android@main to use it.

Please wait a little while until ↓ PR is merged
https://github.com/amyu/setup-android/pull/222

**Comment by amyu** [comment]
https://github.com/amyu/setup-android/actions/runs/6959670030/job/18937427544?pr=222
We reproduced the same environment and confirmed that no error occurred
Please use amyu/setup-android@main and reopen this Issue if you get the same error.

**Comment by amyu** [comment]
Oh, if you like this Library, I hope you will Star it!

**Comment by ezoushen** [comment]
@amyu Thank you for your quick responses and works 🙏. It works like a charm 👍
